services:
  - type: web
    name: mt01-hernandezbackend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        sync: false