services:
  - type: web
    name: mt01_hernandez
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: mongodb+srv://brhernandez_db_user:Gwaposiroan112904.@cluster0.nikpwj7.mongodb.net/mt01?retryWrites=true&w=majority&appName=Cluster0